#!/usr/bin/env python
# coding: utf-8

from __future__ import absolute_import, unicode_literals

templates = []  # Liste des modèles du site à traiter
sections = []  # Sections à remplacer
# Paragraphes autorisant les modèles catégorisants par langue ({{voir| et {{voir/ sont gérés individuellement)
# http://fr.wiktionary.org/wiki/Catégorie:Modèles_de_type_de_mot_du_Wiktionnaire
templates.append('-adj-dem-')
sections.append('adjectif démonstratif')
templates.append('-adj-dém-')
sections.append('adjectif démonstratif')
templates.append('-adj-excl-')
sections.append('adjectif exclamatif')
templates.append('-adj-indef-')
sections.append('adjectif indéfini')
templates.append('-adj-indéf-')
sections.append('adjectif indéfini')
templates.append('-adj-int-')
sections.append('adjectif interrogatif')
templates.append('-adj-num-')
sections.append('adjectif numéral')
templates.append('-adj-pos-')
sections.append('adjectif possessif')
templates.append('-adjectif-')
sections.append('adjectif')
templates.append('-adj-')
sections.append('adjectif')
templates.append('-adv-int-')
sections.append('adverbe interrogatif')
templates.append('-adv-pron-')
sections.append('adverbe pronominal')
templates.append('-adv-rel-')
sections.append('adverbe relatif')
templates.append('-adverbe-')
sections.append('adverbe')
templates.append('-adv-')
sections.append('adverbe')
templates.append('-aff-')
sections.append('affixe')
templates.append('-art-def-')
sections.append('article défini')
templates.append('-art-déf-')
sections.append('article défini')
templates.append('-art-indef-')
sections.append('article indéfini')
templates.append('-art-indéf-')
sections.append('article indéfini')
templates.append('-art-part-')
sections.append('article partitif')
templates.append('-art-')
sections.append('article')
templates.append('-aux-')
sections.append('verbe')
templates.append('-circonf-')
sections.append('circonfixe')
templates.append('-class-')
sections.append('classificateur')
templates.append('-conj-coord-')
sections.append('conjonction de coordination')
templates.append('-conj-')
sections.append('conjonction')
templates.append('-copule-')
sections.append('copule')
templates.append('-dét-')
sections.append('déterminant')
templates.append('-erreur-')
sections.append('erreur')
templates.append('-gismu-')
sections.append('gismu')
templates.append('-inf-')
sections.append('infixe')
templates.append('-interf-')
sections.append('interfixe')
templates.append('-interj-')
sections.append('interjection')
templates.append('-lettre-')
sections.append('lettre')
templates.append('-nom-fam-')
sections.append('nom de famille')
templates.append('-nom-pr-')
sections.append('nom propre')
templates.append('-nom-propre-')
sections.append('nom propre')
templates.append('-nom-sciences-')
sections.append('nom scientifique')
templates.append('-nom-')
sections.append('nom')
templates.append('-num-')
sections.append('numéral')
templates.append('-numér-')
sections.append('numéral')
templates.append('-numéral-')
sections.append('numéral')
templates.append('-part-num-')
sections.append('particule numérale')
templates.append('-part-')
sections.append('particule')
templates.append('-patronyme-')
sections.append('patronyme')
templates.append('-post-')
sections.append('postposition')
templates.append('-préf-')
sections.append('préfixe')
templates.append('-préfixe-')
sections.append('préfixe')
templates.append('-prénom-')
sections.append('prénom')
templates.append('-pré-nom-')
sections.append('pré-nom')
templates.append('-prép-')
sections.append('préposition')
templates.append('-pré-verbe-')
sections.append('pré-verbe')
templates.append('-pronom-adj-')
sections.append('pronom-adjectif')
templates.append('-pronom-dém-')
sections.append('pronom démonstratif')
templates.append('-pronom-indéf-')
sections.append('pronom indéfini')
templates.append('-pronom-int-')
sections.append('pronom interrogatif')
templates.append('-pronom-pers-')
sections.append('pronom personnel')
templates.append('-pronom-pos-')
sections.append('pronom possessif')
templates.append('-pronom-rel-')
sections.append('pronom relatif')
templates.append('-pronom-')
sections.append('pronom')
templates.append('-quantif-')
sections.append('quantificateur')
templates.append('-radical-')
sections.append('radical')
templates.append('-rafsi-')
sections.append('rafsi')
templates.append('-sinogramme-')
sections.append('sinogramme')
templates.append('-subst-pron-pers-')
sections.append('adjectifs')
templates.append('-suf-')
sections.append('suffixe')
templates.append('-suffixe-')
sections.append('suffixe')
templates.append('-symb-')
sections.append('symbole')
templates.append('-symbole-')
sections.append('symbole')
templates.append('-verbe-pr-')
sections.append('verbe pronominal')
templates.append('-verb-pr-')
sections.append('verbe pronominal')
templates.append('-verb-')
sections.append('verbe')
templates.append('-verbe-')
sections.append('verbe')
templates.append('-faux-prov-')
sections.append('faux proverbe')
templates.append('-prov-')
sections.append('proverbe')
templates.append('-loc-phr-')
sections.append('locution-phrase')
templates.append('-loc-')
sections.append('locution')
templates.append('-locution-')
sections.append('locution')
templates.append('-var-typo-')
sections.append('variante typographique')
templates.append('-onoma-')
sections.append('onomatopée')
templates.append('-onomatopée-')
sections.append('onomatopée')
templates.append('-interjection-')
sections.append('interjection')
limit1 = len(templates)
# Paragraphes sans code langue catégorisant, de niveau 3
# http://fr.wiktionary.org/wiki/Catégorie:Modèles_de_contexte
templates.append('-réf-')
sections.append('références')
templates.append('-ref-')
sections.append('références')
templates.append('-références-')
sections.append('références')
templates.append('-sino-dico-')
sections.append('dico sinogrammes')
templates.append('-écrit-')
sections.append('écriture')
templates.append('-voir-')
sections.append('voir aussi')
templates.append('-anagrammes-')
sections.append('anagrammes')
templates.append('-anagr-')
sections.append('anagrammes')
templates.append('-étym-')
sections.append('étymologie')
templates.append('-pron-')
sections.append('prononciation')
templates.append('-décl-')
sections.append('déclinaison')
limit2 = len(templates)
# De niveau 4
templates.append('-compos-')
sections.append('composés')
templates.append('-dial-')
sections.append('variantes dialectales')
templates.append('-faux-amis-')
sections.append('faux-amis')
templates.append('-image-')
sections.append('images vidéo')
templates.append('-trad-')
sections.append('traductions')
templates.append('-dimin-')
sections.append('diminutifs')
templates.append('-drv-int-')
sections.append('dérivés autres langues')
templates.append('-drv-')
sections.append('dérivés')
templates.append('-exp-')
sections.append('expressions')
templates.append('-gent-')
sections.append('gentilés')
templates.append('-hist-')
sections.append('attestations')
templates.append('-holo-')
sections.append('holonymes')
templates.append('-hyper-')
sections.append('hyperonymes')
templates.append('-hypo-')
sections.append('hyponymes')
templates.append('-méro-')
sections.append('méronymes')
templates.append('-noms-vern-')
sections.append('noms vernaculaires')
templates.append('-ortho-arch-')
sections.append('anciennes orthographes')
templates.append('-paro-')
sections.append('paronymes')
templates.append('-phrases-')
sections.append('phrases')
templates.append('-q-syn-')
sections.append('quasi-synonymes')
templates.append('-syn-')
sections.append('synonymes')
templates.append('-tran-')
sections.append('transcriptions')
templates.append('-trans-')
sections.append('transcriptions')
templates.append('-translit-')
sections.append('translittérations')
templates.append('-tropo-')
sections.append('troponymes')
templates.append('-var-ortho-')
sections.append('variantes orthographiques')
templates.append('-var-ortho-')
sections.append('variantes ortho')
templates.append('-var-')
sections.append('variantes')
templates.append('-vidéo-')
sections.append('images vidéo')
templates.append('-voc-')
sections.append('vocabulaire')
templates.append('-voc-')
sections.append('vocabulaire apparenté')
templates.append('-abréviation-')
sections.append('abréviations')
templates.append('-ant-')
sections.append('antonymes')
templates.append('-abrév-')
sections.append('abréviations')
templates.append('-dial-')
sections.append('dial')
templates.append('-apr-')
sections.append('apparentés')
templates.append('-conjug-')
sections.append('conjugaison')
templates.append('-cit-')
sections.append('citations')
templates.append('vidéos')
sections.append('vidéos')
templates.append('augmentatifs')
sections.append('augmentatifs')
templates.append('diminutifs')
sections.append('diminutifs')
templates.append('-notes-')
sections.append('notes')
templates.append('-note-')
sections.append('notes')
# Avec code langue
templates.append('-homo-')
sections.append('homophones')
limit3 = len(templates)
templates.append('trad-trier')
sections.append('traductions à trier')
limit4 = len(templates)
templates.append('caractère')
templates.append('langue')
templates.append('S')

# https://fr.wiktionary.org/wiki/Catégorie:Modèles_étymologiques
etymologyTemplates = [u'étcompcat', 'étyl', 'étylp', 'louchébem', 'reverlanisation', 'verlan']
etymologyTemplatesWithLanguageAtLang = ['compos', 'composé de', 'deet', 'date'] #, 'siècle'
etymologyTemplatesInSatelliteWords = ['abréviation', 'abréviation de', 'acronyme', 'apocope', 'aphérèse', 'ellipse', 'par ellipse', 'sigle']
etymologyTemplatesWithLanguageAtFirst = etymologyTemplatesInSatelliteWords + ['agglutination', 'antonomase', \
    'déglutination', 'mot-valise', 'parataxe', 'syncope', 'univerbation']
etymologyTemplatesWithLanguageAtSecond = ['dénominal', 'dénominal de', 'déverbal', 'déverbal de', 'déverbal sans suffixe']

# Modèles qui ne sont pas des titres de paragraphes
templates.append('?')
templates.append('doute')
templates.append('m')
templates.append('f')
templates.append('vérifier')
templates.append('formater')
templates.append('suppression')
templates.append('supp')
templates.append('SI')
templates.append('supprimer ?')
templates.append('PàS')
templates.append('(')
templates.append(')')
templates.append('trad-début')
templates.append('trad-fin')
templates.append('titre incorrect')
templates.append('trad--')
templates.append('trad-')
templates.append('trad+')
templates.append('trad')
templates.append('préciser')
templates.append('cf')
templates = templates + etymologyTemplatesWithLanguageAtLang

limit5 = len(templates)
templates.append('comparatif')
templates.append('superlatif')
templates.append('beaucoup plus courant')
templates.append('plus courant')
templates.append('beaucoup moins courant')
templates.append('moins courant')
templates.append('b-pl-cour')
templates.append('pl-cour')
templates.append('b-m-cour')
templates.append('m-cour')
templates.append('mf')
templates.append('n')
templates.append('c')
templates.append('pl-rare')
templates.append('plus rare')
templates.append('pluriel')
limit6 = len(templates)
templates.append('pron')
templates.append('écouter')
templates.append('référence nécessaire')
templates.append('réf?')
templates.append('réf ?')
templates.append('refnec')
templates.append('réfnéc')
templates.append('source?')
templates.append('réfnéc')
# http://fr.wiktionary.org/wiki/Catégorie:Modèles_de_domaine_d'utilisation
templates.append('1ergroupe')
templates.append('2egroupe')
templates.append('3egroupe')
templates.append('Antiquité')
templates.append('BD')
templates.append('BDD')
templates.append('CB')
templates.append('Internet')
templates.append('Moyen Âge')
templates.append('Scrabble')
templates.append('ablat')
templates.append('ablatif')
templates.append('accord genre ?')
templates.append('accus')
templates.append('accusatif')
templates.append('acoustique')
templates.append('admin')
templates.append('administration')
templates.append('adverbes de lieu')
templates.append('adverbes de temps')
templates.append('adverbes interrogatif')
templates.append('affectueux')
templates.append('agri')
templates.append('agriculture')
templates.append('agronomie')
templates.append('alcools')
templates.append('algues‎')
templates.append('algèbre linéaire')
templates.append('algèbre‎')
templates.append('aliments‎')
templates.append('allatif')
templates.append('alliages')
templates.append('alpi')
templates.append('alpinisme')
templates.append('anal')
templates.append('analogie')
templates.append('analyse')
templates.append('anat')
templates.append('anatomie')
templates.append('anciennes divisions')
templates.append('anciennes localités')
templates.append('angl')
templates.append('anglicisme')
templates.append('anglicismes informatiques')
templates.append('animaux')
templates.append('animé')
templates.append('anthro')
templates.append('anthropologie')
templates.append('antilopes')
templates.append('antiq')
templates.append('antiquité')
templates.append('apiculture')
templates.append('araignées')
templates.append('arboriculture')
templates.append('arbres')
templates.append('arch')
templates.append('archaïque')
templates.append('archaïsme')
templates.append('archi')
templates.append('architecture des ordinateurs')
templates.append('architecture')
templates.append('archéo')
templates.append('archéologie')
templates.append('argot militaire')
templates.append('argot policier')
templates.append('argot polytechnicien')
templates.append('argot scolaire')
templates.append('argot')
templates.append('argots')
templates.append('arithmétique')
templates.append('arme')
templates.append('armement')
templates.append('armes blanches')
templates.append('armes à feu')
templates.append('armes')
templates.append('arthropodes')
templates.append('artillerie')
templates.append('artistes')
templates.append('arts martiaux')
templates.append('arts')
templates.append('assurance')
templates.append('astrol')
templates.append('astrologie')
templates.append('astron')
templates.append('astronautique')
templates.append('astronomie')
templates.append('astrophysique')
templates.append('athlé')
templates.append('athlétisme')
templates.append('atomes')
templates.append('audiovis')
templates.append('audiovisuel')
templates.append('automatique')
templates.append('automo')
templates.append('automobile')
templates.append('auxiliaire')
templates.append('au pluriel uniquement')
templates.append('au singulier uniquement')
templates.append('aviat')
templates.append('aviation')
templates.append('avions')
templates.append('aéro')
templates.append('aéronautique')
templates.append('aïkido')
templates.append('bactéries')
templates.append('bactério')
templates.append('bactériologie')
templates.append('badminton')
templates.append('bandes dessinées')
templates.append('base-ball')
templates.append('baseball')
templates.append('bases de données')
templates.append('basket')
templates.append('bateaux')
templates.append('beaux-arts')
templates.append('bibliothéconomie')
templates.append('bières')
templates.append('bijou')
templates.append('bijouterie')
templates.append('billard')
templates.append('biochimie')
templates.append('biol')
templates.append('biologie cellulaire')
templates.append('biologie')
templates.append('biophysique')
templates.append('bivalves')
templates.append('boissons')
templates.append('botan')
templates.append('botanique')
templates.append('boucherie')
templates.append('bouddhisme')
templates.append('boulangerie')
templates.append('bourrellerie')
templates.append('bovins')
templates.append('bowling')
templates.append('boxe')
templates.append('bridge')
templates.append('broderie')
templates.append('bâtiment')
templates.append('cactus')
templates.append('calendrier')
templates.append('camélidés')
templates.append('canoe')
templates.append('canoë')
templates.append('canoë-kayak')
templates.append('capoeira')
templates.append('capoeira')
templates.append('caprins')
templates.append('cardin')
templates.append('cardinal')
templates.append('carnivore')
templates.append('cartes')
templates.append('cartographie')
templates.append('catch')
templates.append('catholicisme')
templates.append('caténatif')
templates.append('cavalerie')
templates.append('cervidés')
templates.append('chameaux')
templates.append('champignons')
templates.append('charpente')
templates.append('charpenterie')
templates.append('chasse')
templates.append('chats')
templates.append('chaussures')
templates.append('chauves-souris')
templates.append('chaînes de montagnes')
templates.append('chemin de fer')
templates.append('chevaux')
templates.append('chiens')
templates.append('chim')
templates.append('chimie inorganique')
templates.append('chimie organique')
templates.append('chimie physique')
templates.append('chimie')
templates.append('chir')
templates.append('chiromancie')
templates.append('chirurgie')
templates.append('christianisme')
templates.append('chronologie')
templates.append('chênes')
templates.append('cigognes')
templates.append('ciné')
templates.append('cinéma')
templates.append('cirque')
templates.append('cnidaires')
templates.append('cocktails')
templates.append('coiffure')
templates.append('colorimétrie')
templates.append('coléoptères')
templates.append('combat')
templates.append('comm')
templates.append('commerce')
templates.append('commerces')
templates.append('comparatif de')
templates.append('composants électriques')
templates.append('composants électroniques')
templates.append('composants')
templates.append('compta')
templates.append('comptabilité')
templates.append('condiments')
templates.append('confiserie')
templates.append('confiseries')
templates.append('conifères')
templates.append('conjugaison')
templates.append('constr')
templates.append('construction')
templates.append('contemporain')
templates.append('copropriété')
templates.append('coquillages')
templates.append('cordonnerie')
templates.append('cosm')
templates.append('cosmétique')
templates.append('cosmétologie')
templates.append('couche application')
templates.append('couche liaison')
templates.append('couche physique')
templates.append('couche présentation')
templates.append('couche réseau')
templates.append('couche session')
templates.append('couche transport')
templates.append('cour')
templates.append('courant')
templates.append('cours d’eau')
templates.append('course à pied')
templates.append('cout')
templates.append('couture')
templates.append('couverture')
templates.append('couvre-chefs')
templates.append('crabes')
templates.append('crapauds')
templates.append('cricket')
templates.append('crimes')
templates.append('criminels')
templates.append('cristallographie')
templates.append('critiqué')
templates.append('crustacés')
templates.append('cryptomonnaie')
templates.append('cryptomonnaies')
templates.append('créatures')
templates.append('cuis')
templates.append('cuisine')
templates.append('culturisme')
templates.append('cycl')
templates.append('cyclisme')
templates.append('cygnes')
templates.append('cépages')
templates.append('céphalopodes')
templates.append('céramique')
templates.append('céréales')
templates.append('cétacés')
templates.append('danse')
templates.append('danses')
templates.append('datif')
templates.append('dentisterie')
templates.append('dermat')
templates.append('dermatologie')
templates.append('desserts')
templates.append('dessin')
templates.append('dialectes')
templates.append('didact')
templates.append('didactique')
templates.append('dim-lex')
templates.append('diminutif')
templates.append('dinosaures')
templates.append('dinosaures')
templates.append('diplomatie')
templates.append('diplomatie')
templates.append('diptote')
templates.append('distinctions')
templates.append('divinités')
templates.append('documents')
templates.append('drogue')
templates.append('drogues')
templates.append('droit de propriété')
templates.append('droit du travail')
templates.append('droit féodal')
templates.append('droit')
templates.append('dén')
templates.append('dénombrable')
templates.append('dépendant')
templates.append('déris')
templates.append('dérision')
templates.append('dérision')
templates.append('déserts')
templates.append('désuet')
templates.append('détroits')
templates.append('embryologie')
templates.append('enclitique')
templates.append('enfantin')
templates.append('entom')
templates.append('entomol')
templates.append('entomologie')
templates.append('enzymes')
templates.append('escalade')
templates.append('escrime')
templates.append('ethnobiologie')
templates.append('ethnologie')
templates.append('ethnonymes')
templates.append('euphorbes')
templates.append('euphémisme')
templates.append('ex-rare')
templates.append('exag')
templates.append('exagératif')
templates.append('exagération')
templates.append('expression')
templates.append('extrêmement rare')
templates.append('fam')
templates.append('fami')
templates.append('familier')
templates.append('famille')
templates.append('fanta')
templates.append('fantastique')
templates.append('fauconnerie')
templates.append('ferro')
templates.append('ferroviaire')
templates.append('fig.')
templates.append('figure')
templates.append('figures')
templates.append('figuré')
templates.append('finan')
templates.append('finance')
templates.append('finances')
templates.append('fisc')
templates.append('fiscalité')
templates.append('flamants')
templates.append('fleurs')
templates.append('fleuve')
templates.append('fm ?')
templates.append('fonderie')
templates.append('fontainerie')
templates.append('foot')
templates.append('football américain')
templates.append('football canadien')
templates.append('football')
templates.append('footing')
templates.append('foresterie')
templates.append('formel')
templates.append('fortification')
templates.append('franc-maçonnerie')
templates.append('fromages')
templates.append('fruits')
templates.append('félins')
templates.append('gall')
templates.append('gallicisme')
templates.append('gastro')
templates.append('gastron')
templates.append('gastronomie')
templates.append('gastéropodes')
templates.append('genre ?')
templates.append('genre')
templates.append('genres musicaux')
templates.append('gentilés ?')
templates.append('gentilés')
templates.append('geog')    # à remplacer ?
templates.append('geol')
templates.append('germanisme')
templates.append('giraffidés')
templates.append('glaciol')
templates.append('glaciologie')
templates.append('gladiateurs')
templates.append('golf')
templates.append('golfe')
templates.append('golfes')
templates.append('grades')
templates.append('gram')
templates.append('grammaire')
templates.append('graphe')
templates.append('gravure')
templates.append('grenouilles')
templates.append('grues')
templates.append('guerre')
templates.append('gymnastique')
templates.append('gynécologie')
templates.append('gâteaux')
templates.append('gén-indén')
templates.append('génit')
templates.append('génitif')
templates.append('génitif')
templates.append('généal')
templates.append('généalogie')
templates.append('généralement indénombrable')
templates.append('généralement pluriel')
templates.append('généralement singulier')
templates.append('génétique')
templates.append('géog')
templates.append('géographie')
templates.append('géol')
templates.append('géologie')
templates.append('géom')
templates.append('géomatique')
templates.append('géométrie')
templates.append('géoph')
templates.append('géophysique')
templates.append('hand')
templates.append('handball')
templates.append('handicap')
templates.append('handisport')
templates.append('hapax')
templates.append('herpétologie')
templates.append('hindouisme')
templates.append('hippisme')
templates.append('hippologie')
templates.append('hispanisme')
templates.append('hist')
templates.append('hist')
templates.append('histoire')
templates.append('histol')
templates.append('histologie')
templates.append('histologie')
templates.append('hockey sur glace')
templates.append('hockey')
templates.append('horlogerie')
templates.append('horticulture')
templates.append('humour')
templates.append('hydraulique')
templates.append('hydrobiologie')
templates.append('hygiène')
templates.append('hyperb')
templates.append('hyperbole')
templates.append('hérald')
templates.append('héraldique')
templates.append('hérons')
templates.append('i')
templates.append('ibis')
templates.append('ichtyo')
templates.append('ichtyologie')
templates.append('idiomatique')
templates.append('idiotisme')
templates.append('illégalité')
templates.append('impers')
templates.append('impersonnel')
templates.append('impr')
templates.append('imprimerie')
templates.append('improprement')
templates.append('inanimé')
templates.append('indus')
templates.append('industrie pétrolière')
templates.append('industrie')
templates.append('indéc')
templates.append('indécl')
templates.append('indéclinable')
templates.append('indéfini')
templates.append('indén')
templates.append('indénombrable')
templates.append('info')
templates.append('infographie')
templates.append('inform')
templates.append('informatique')
templates.append('informatique')
templates.append('informel')
templates.append('injur')
templates.append('injurieux')
templates.append('insecte')
templates.append('insectes')
templates.append('instrumental')
templates.append('instruments de mesure')
templates.append('instruments')
templates.append('insultes')
templates.append('intelligence artificielle')
templates.append('interjection')
templates.append('internet')
templates.append('intrans')
templates.append('intransitif')
templates.append('iron')
templates.append('ironie')
templates.append('ironique')
templates.append('irrég')
templates.append('irrégulier')
templates.append('islam')
templates.append('jardi')
templates.append('jardin')
templates.append('jardinage')
templates.append('jazz')
templates.append('jeu de paume')
templates.append('jeu vidéo')
templates.append('jeux de cartes')
templates.append('jeux vidéo')
templates.append('jeux')
templates.append('joaillerie')
templates.append('jogging')
templates.append('jonglage')
templates.append('jonglerie')
templates.append('jouets')
templates.append('journal')
templates.append('journalisme')
templates.append('judaïsme')
templates.append('judo')
templates.append('juri')
templates.append('jurisprudence')
templates.append('just')
templates.append('justice')
templates.append('karaté')
templates.append('kung-fu')
templates.append('langage Java')
templates.append('langage SMS')
templates.append('langages informatiques')
templates.append('langues')
templates.append('latinisme')
templates.append('lexicographie')
templates.append('lianes')
templates.append('ling')
templates.append('linguistique')
templates.append('litote')
templates.append('litt')
templates.append('littér')
templates.append('littéraire')
templates.append('littérature')
templates.append('liturgie')
templates.append('livre')
templates.append('locat')
templates.append('locatif')
templates.append('logi')
templates.append('logique')
templates.append('logistique')
templates.append('loisirs')
templates.append('lutherie')
templates.append('législation')
templates.append('légumes')
templates.append('léporidé')
templates.append('lézards')
templates.append('machines')
templates.append('magnétisme')
templates.append('mah-jong')
templates.append('mahjong')
templates.append('maintenance')
templates.append('majong')
templates.append('maladie')
templates.append('maladies de l’œil')
templates.append('maladies')
templates.append('mammifères')
templates.append('manège')
templates.append('marbrerie')
templates.append('mari')
templates.append('marine')
templates.append('marketing')
templates.append('maroquinerie')
templates.append('marsupial')
templates.append('math')
templates.append('mathématiques')
templates.append('maçon')
templates.append('maçonnerie')
templates.append('menuiserie')
templates.append('mercatique')
templates.append('mers')
templates.append('meuble')
templates.append('meuble héraldique')
templates.append('mf ?')
templates.append('mf ?')
templates.append('microbiologie')
templates.append('mili')
templates.append('milit')
templates.append('militaire')
templates.append('minér')
templates.append('minéral')
templates.append('minéralogie')
templates.append('minéraux')
templates.append('miroiterie')
templates.append('mobilier')
templates.append('mollusques')
templates.append('monarchie')
templates.append('monnaies')
templates.append('montagnes')
templates.append('morphologie végétale')
templates.append('motocyclisme')
templates.append('mouches')
templates.append('muscle')
templates.append('musculation')
templates.append('musi')
templates.append('musiciens')
templates.append('musique')
templates.append('musiques')
templates.append('myco')
templates.append('mycol')
templates.append('mycologie')
templates.append('mythol')
templates.append('mythologie')
templates.append('mythologie égyptienne')
templates.append('mythologie grecque')
templates.append('méca')
templates.append('mécanique')
templates.append('mécoupure')
templates.append('méd')
templates.append('méde')
templates.append('médecine non conv')
templates.append('médecine')
templates.append('média')
templates.append('médicaments')
templates.append('méduses')
templates.append('mélio')
templates.append('mélioratif')
templates.append('métal')
templates.append('métallurgie')
templates.append('métaph')
templates.append('métaphore')
templates.append('métaplasmes')
templates.append('méton')
templates.append('métonymie')
templates.append('métrol')
templates.append('métrologie')
templates.append('météo')
templates.append('météorol')
templates.append('météorologie')
templates.append('narratol')
templates.append('narratologie')
templates.append('nata')
templates.append('natation')
templates.append('navig')
templates.append('navigation')
templates.append('neuro')
templates.append('neurologie')
templates.append('noblesse')
templates.append('nom')
templates.append('nombre')
templates.append('nomin')
templates.append('nominatif')
templates.append('nosologie')
templates.append('note-gentilé')
templates.append('novlangue')
templates.append('nuages')
templates.append('nucl')
templates.append('nucléaire')
templates.append('numis')
templates.append('numismatique')
templates.append('nutrition')
templates.append('néol litt')
templates.append('néol')
templates.append('néologisme')
templates.append('obsolète')
templates.append('obstétrique')
templates.append('oenol')
templates.append('oenologie')
templates.append('oies')
templates.append('oiseaux')
templates.append('ophtalmologie')
templates.append('opti')
templates.append('optique')
templates.append('optométrie')
templates.append('ordin')
templates.append('ordinal')
templates.append('orfèvrerie')
templates.append('ornit')
templates.append('ornithologie')
templates.append('outils')
templates.append('p-us')
templates.append('palindrome')
templates.append('palmiers')
templates.append('paléo')
templates.append('paléographite')
templates.append('paléontol')
templates.append('paléontologie')
templates.append('palmipèdes')
templates.append('papeterie')
templates.append('papillons')
templates.append('papèterie')
templates.append('par analogie')
templates.append('par dérision')
templates.append('par métonymie')
templates.append('par plaisanterie')
templates.append('parfumerie')
templates.append('passif')
templates.append('pathologie')
templates.append('patin')
templates.append('paume')
templates.append('pays')
templates.append('pêche à la ligne')
templates.append('peinture')
templates.append('perroquets')
templates.append('peu attesté')
templates.append('peu usité')
templates.append('peuplier')
templates.append('peupliers')
templates.append('pharma')
templates.append('pharmacie')
templates.append('pharmacol')
templates.append('pharmacologie')
templates.append('philo')
templates.append('philosophie')
templates.append('phobies')
templates.append('phon')
templates.append('phonologie')
templates.append('phonétique')
templates.append('photo')
templates.append('photographie')
templates.append('phys')
templates.append('physique des réacteurs')
templates.append('physio')
templates.append('physiol')
templates.append('physiologie')
templates.append('physique')
templates.append('phyton')
templates.append('phytonimie')
templates.append('phytopathologie')
templates.append('plais')
templates.append('plaisanterie')
templates.append('planche à neige')
templates.append('planche à roulettes')
templates.append('plans d’eau')
templates.append('plante')
templates.append('plantes aromatiques')
templates.append('plantes')
templates.append('plongée')
templates.append('plurale tantum')
templates.append('pluriel ?')
templates.append('poet')
templates.append('points cardinaux')
templates.append('poires')
templates.append('poisson')
templates.append('poissons')
templates.append('poker')
templates.append('police')
templates.append('polit')
templates.append('politique')
templates.append('pommes')
templates.append('ponctuations')
templates.append('popu')
templates.append('populaire')
templates.append('porcins')
templates.append('positions')
templates.append('poés')
templates.append('poésie')
templates.append('poét')
templates.append('poétique')
templates.append('poules')
templates.append('ppart')
templates.append('presse')
templates.append('prestidigitation')
templates.append('prison')
templates.append('prnl')
templates.append('probabilités')
templates.append('procédure')
templates.append('prog')
templates.append('programmation')
templates.append('pronl')
templates.append('pronominal')
templates.append('propre')
templates.append('propriété')
templates.append('protestantisme')
templates.append('protocoles')
templates.append('protéines')
templates.append('prov')
templates.append('proverbe')
templates.append('proverbes')
templates.append('proverbial')
templates.append('préhistoire')
templates.append('prépositionnel')
templates.append('psych')
templates.append('psychanalyse')
templates.append('psychia')
templates.append('psychiatrie')
templates.append('psycho')
templates.append('psycho')
templates.append('psychol')
templates.append('psychologie')
templates.append('psychotropes')
templates.append('publicité')
templates.append('pâtes')
templates.append('pâtisserie')
templates.append('pédol')
templates.append('pédologie')
templates.append('péjoratif')
templates.append('pélicans')
templates.append('pétanque')
templates.append('pétro')
templates.append('pétrochimie')
templates.append('pêch')
templates.append('pêche')
templates.append('pêches')
templates.append('radio')
templates.append('raies')
templates.append('rapaces')
templates.append('rare')
templates.append('reli')
templates.append('religieux')
templates.append('religion')
templates.append('religions')
templates.append('reliure')
templates.append('renseignement')
templates.append('repro')
templates.append('reproduction')
templates.append('reptiles')
templates.append('rhéto')
templates.append('rhétorique')
templates.append('robotiques')
templates.append('roches')
templates.append('rongeur')
templates.append('rugby')
templates.append('running')
templates.append('récip')
templates.append('réciproque')
templates.append('réfl')
templates.append('réflexif')
templates.append('réfléchi')
templates.append('région')
templates.append('réseau')
templates.append('réseaux informatiques')
templates.append('réseaux')
templates.append('saccusatif')
templates.append('saisons')
templates.append('salades')
templates.append('salles')
templates.append('sandwitchs')
templates.append('sans pron')
templates.append('satellites')
templates.append('saules')
templates.append('saut en hauteur')
templates.append('sci-fi')
templates.append('science-fiction')
templates.append('sciences')
templates.append('scientifiques')
templates.append('scol')
templates.append('scolaire')
templates.append('scul')
templates.append('sculpture')
templates.append('sdatif')
templates.append('seigneuries')
templates.append('sentiments')
templates.append('serpents')
templates.append('serru')
templates.append('serrurerie')
templates.append('sexe')
templates.append('sexualité')
templates.append('singes')
templates.append('singulare tantum')
templates.append('sinstrumental')
templates.append('skate')
templates.append('skateboard')
templates.append('ski alpin')
templates.append('ski de fond')
templates.append('snow')
templates.append('snowboard')
templates.append('socio')
templates.append('sociol')
templates.append('sociologie')
templates.append('soldats')
templates.append('sout')
templates.append('soutenu')
templates.append('spatules')
templates.append('sport de combat')
templates.append('sport de glisse')
templates.append('sport mécanique')
templates.append('sport')
templates.append('sportifs')
templates.append('sports de combat')
templates.append('sports de glisse')
templates.append('sports')
templates.append('squelette')
templates.append('stat')
templates.append('statistiques')
templates.append('stéréochimie')
templates.append('stéréotomie')
templates.append('stéréotype')
templates.append('substances')
templates.append('superlatif de')
templates.append('supprimer-déf ?')
templates.append('surf')
templates.append('sylvi')
templates.append('sylviculture')
templates.append('symboles unités')
templates.append('t')
templates.append('t/i')
templates.append('taille de pierre')
templates.append('tauromachie')
templates.append('td')
templates.append('tech')
templates.append('technique')
templates.append('techno')
templates.append('technol')
templates.append('technologie')
templates.append('technologie des réacteurs')
templates.append('temps géologiques')
templates.append('temps')
templates.append('tennis de table')
templates.append('tennis')
templates.append('tératologie')
templates.append('term')
templates.append('terme non standard')
templates.append('territoires')
templates.append('text')
templates.append('textile')
templates.append('textiles')
templates.append('thermodynamique')
templates.append('théol')
templates.append('théologie')
templates.append('théorie des graphes')
templates.append('théât')
templates.append('théâtre')
templates.append('tind')
templates.append('tir à l’arc')
templates.append('tissage')
templates.append('tissus')
templates.append('tonnellerie')
templates.append('topo')
templates.append('topographie')
templates.append('topologie')
templates.append('topon')
templates.append('toponymie')
templates.append('tortues')
templates.append('tour')
templates.append('tourisme')
templates.append('tr-dir')
templates.append('tr-ind')
templates.append('tr-indir')
templates.append('trad-exe')
templates.append('trans')
templates.append('transit')
templates.append('transitif')
templates.append('transp')
templates.append('transport')
templates.append('transports')
templates.append('travail')
templates.append('très familier')
templates.append('très rare')
templates.append('très très rare')
templates.append('très-rare')
templates.append('type')
templates.append('typo')
templates.append('typographie')
templates.append('télé')
templates.append('télécom')
templates.append('télécommunications')
templates.append('téléphonie')
templates.append('télévision')
templates.append('typographie et informatique')
templates.append('ufologie')
templates.append('un os')
templates.append('unités')
templates.append('urban')
templates.append('urbanisme')
templates.append('usage critiqué')
templates.append('usinage')
templates.append('usines')
templates.append('ustensiles')
templates.append('vaudou')
templates.append('vents')
templates.append('verrerie')
templates.append('vers')
templates.append('versification')
templates.append('viandes')
templates.append('vieilli')
templates.append('vieux')
templates.append('vins')
templates.append('virologie')
templates.append('virus')
templates.append('viticulture')
templates.append('vitrerie')
templates.append('vocat')
templates.append('vocatif')
templates.append('voitures')
templates.append('volcanologie')
templates.append('volley')
templates.append('volley-ball')
templates.append('vulg')
templates.append('vulgaire')
templates.append('véhicules')
templates.append('vétérinaire')
templates.append('vête')
templates.append('vêtements')
templates.append('wiki')
templates.append('xénarthres')
templates.append('yoga')
templates.append('zool')
templates.append('zoologie')
templates.append('zootechnie')
templates.append('ébauche-trad-exe')
templates.append('échecs')
templates.append('écol')
templates.append('écologie')
templates.append('écon')
templates.append('économie')
templates.append('écureuils')
templates.append('édifices')
templates.append('édition')
templates.append('éduc')
templates.append('éducation')
templates.append('élatif')
templates.append('élec')
templates.append('électoraux')
templates.append('électricité')
templates.append('électro')
templates.append('électron')
templates.append('électronique')
templates.append('électrot')
templates.append('électrotech')
templates.append('électrotechnique')
templates.append('élevage')
templates.append('éléments')
templates.append('épices')
templates.append('épithète')
templates.append('équi')
templates.append('équitation')
templates.append('établissements')
templates.append('étoiles')
templates.append('œnologie')

limit7 = len(templates)
# Code langue quoi qu'il arrive
templates.append('...')
templates.append('ébauche-syn')
templates.append('non standard')
templates.append('ébauche-trans')
templates.append('ébauche-étym-nom-scientifique')
templates.append('ébauche-étym')
templates.append('ébauche-déf')
templates.append('ébauche-exe')
templates.append('ébauche-pron')
templates.append('ébauche')
templates.append('Région ?')
templates.append('région ?')

limit8 = len(templates)
# Code langue si étymologie
templates = templates + etymologyTemplatesWithLanguageAtFirst + etymologyTemplatesWithLanguageAtSecond

limit9 = len(templates)
# Modèles régionaux, avec "nocat" pour les prononciations
templates.append('Acadie')
templates.append('Afrique')
templates.append('Afrique du Sud')
templates.append('Algérie')
templates.append('Allemagne')
templates.append('Alsace')
templates.append('Amérique centrale')
templates.append('Amérique du Nord')
templates.append('Amérique du Sud')
templates.append('Amérique latine')
templates.append('Anjou')
templates.append('Antilles')
templates.append('Aquitaine')
templates.append('Argentine')
templates.append('Australie')
templates.append('Autriche')
templates.append('Auvergne')
templates.append('Baléares')
templates.append('Belgique')
templates.append('Belize')
templates.append('Bénin')
templates.append('Berry')
templates.append('Bolivie')
templates.append('Bordelais')
templates.append('Bourgogne')
templates.append('Brésil')
templates.append('Bretagne')
templates.append('Burkina Faso')
templates.append('Cameroun')
templates.append('Canada')
templates.append('Catalogne')
templates.append('Champagne')
templates.append('Chef-Boutonne')
templates.append('Chili')
templates.append('Chine')
templates.append('Colombie')
templates.append('Commonwealth')
templates.append('Congo')
templates.append('Congo-Brazzaville')
templates.append('Congo-Kinshasa')
templates.append('Corée du Nord')
templates.append('Corée du Sud')
templates.append('Corse')
templates.append('Costa Rica')
templates.append('Côte d’Ivoire')
templates.append('Cuba')
templates.append('Écosse')
templates.append('Espagne')
templates.append('États-Unis')
templates.append('Europe')
templates.append('France')
templates.append('Franche-Comté')
templates.append('Gascogne')
templates.append('Gaspésie')
templates.append('Guadeloupe')
templates.append('Guinée')
templates.append('Guyane')
templates.append('Haïti')
templates.append('Honduras')
templates.append('Hongrie')
templates.append('Île-de-France')
templates.append('Inde')
templates.append('Irlande')
templates.append('‎Israël')
templates.append('Jamaïque')
templates.append('Japon')
templates.append('Languedoc-Roussillon')
templates.append('Le Mans')
templates.append('Lettonie')
templates.append('Liban')
templates.append('Liechtenstein')
templates.append('Limousin')
templates.append('Lituanie')
templates.append('Lorraine')
templates.append('Louisiane')
templates.append('Luxembourg')
templates.append('Lyonnais')
templates.append('Madagascar')
templates.append('Maghreb')
templates.append('Mali')
templates.append('Maroc')
templates.append('Marseille')
templates.append('Maurice')
templates.append('Mauritanie')
templates.append('Mayotte')
templates.append('Mexique')
templates.append('Midi')
templates.append('Midi toulousain')
templates.append('Moldavie')
templates.append('Namibie')
templates.append('Nantes')
templates.append('Navarre')
templates.append('Niger')
templates.append('Nigéria')
templates.append('Normandie')
templates.append('Nouvelle-Calédonie')
templates.append('Nouvelle-Zélande')
templates.append('Occitanie')
templates.append('Océanie')
templates.append('Orient')
templates.append('Paraguay')
templates.append('Paris')
templates.append('Pays-Bas')
templates.append('Pays basque')
templates.append('Pérou')
templates.append('Picardie')
templates.append('Poitou')
templates.append('Pologne')
templates.append('Polynésie française')
templates.append('Porto Rico')
templates.append('Portugal')
templates.append('Provence')
templates.append('Québec')
templates.append('Quercy')
templates.append('République dominicaine')
templates.append('République tchèque')
templates.append('Réunion')
templates.append('Roumanie')
templates.append('Royaume-Uni')
templates.append('Russie')
templates.append('Salvador')
templates.append('Savoie')
templates.append('Sénégal')
templates.append('Slovaquie')
templates.append('Sologne')
templates.append('Suède')
templates.append('Suisse')
templates.append('Taïwan')
templates.append('Tchad')
templates.append('Togo')
templates.append('Transnistrie')
templates.append('Tunisie')
templates.append('Uruguay')
templates.append('Valence')
templates.append('Var')
templates.append('Velay')
templates.append('Venezuela')
templates.append('Viêt Nam')
templates.append('Vosges')

# Abréviations (python pagegenerators.py -redirectonly:Template:!)
templates.append('EU')
templates.append('FR')
templates.append('BE')
templates.append('CH')
templates.append('QC')
templates.append('CA')
templates.append('US')
templates.append('USA')
templates.append('UK')
templates.append('GB')
templates.append('AU')
templates.append('NZ')
templates.append('IE')
# Modèles de pronociation à synchroniser
templates.append('fr-verbe-flexion')

limit10 = len(templates)  # Somme des modèles traités
'''
# TODO : non traités

    # Sans code langue
        Modele.append('voir')
        Modele.append('spécialement')
        Modele.append('région')
        Modele.append('régio')
        Modele.append('régional')

    # Utilisés sur la ligne de forme (parfois sans parenthèses)
        Modele.append('déterminé')
        Modele.append('indéterminé')
        Modele.append('dét')
        Modele.append('indét')
        Modele.append('perfectif')
        Modele.append('imperfectif')
        Modele.append('perf')
        Modele.append('imperf')

    # à synchroniser
        Modele.append('T')...
'''

numbers = []
numbers.append('au singulier')
numbers.append('d')
numbers.append('fplur')
numbers.append('fsing')
numbers.append('indén')
numbers.append('indénombrable')
numbers.append('invar')
numbers.append('invariable')
numbers.append('mplur')
numbers.append('msing')
numbers.append('nombre')
numbers.append('nplur')
numbers.append('nsing')
numbers.append('p')
numbers.append('plurale tantum')
numbers.append('pluriel')
numbers.append('pluriel ?')
numbers.append('s')
numbers.append('singulier')
numbers.append('singulare tantum')
numbers.append('sp')

genders = []
genders.append('c')
genders.append('f')
genders.append('fplur')
genders.append('fsing')
genders.append('genre')
genders.append('m')
genders.append('mf')
genders.append('mf ?')
genders.append('fm ?')
genders.append('mplur')
genders.append('msing')
genders.append('n')
genders.append('nplur')
genders.append('nsing')
