#!/usr/bin/env python
# coding: utf-8

old_templates = []
new_templates = []

# English
old_templates.append('cite web')
new_templates.append('lien web')

old_templates.append('citeweb')
new_templates.append('lien web')

old_templates.append('cite news')
new_templates.append('article')

old_templates.append('citenews')
new_templates.append('article')

old_templates.append('cite journal')
new_templates.append('article')

old_templates.append('cite magazine')
new_templates.append('article')

old_templates.append('cite newspaper')
new_templates.append('article')

old_templates.append('cite video')
new_templates.append('lien vidéo')

old_templates.append('cite episode')
new_templates.append('citation épisode')

old_templates.append('cite arXiv')
new_templates.append('lien arXiv')

old_templates.append('cite press release')
new_templates.append('lien web')

old_templates.append('cite pr')
new_templates.append('lien web')

old_templates.append('web site')
new_templates.append('lien web')

old_templates.append('cite conference')
new_templates.append('lien conférence')

old_templates.append('cite book')
new_templates.append('ouvrage')

old_templates.append('cite Book')
new_templates.append('ouvrage')

old_templates.append('cite')
new_templates.append('ouvrage')

old_templates.append('cite encyclopedia')
new_templates.append('article encyclopédique')

old_templates.append('quote')
new_templates.append('citation bloc')

# de
old_templates.append('internetquelle')
new_templates.append('lien web')

# es
old_templates.append('cita noticia')
new_templates.append('article')

old_templates.append('cita web')
new_templates.append('lien web')

# it
old_templates.append('cita pubblicazione')
new_templates.append('article')

old_templates.append('cita libro')
new_templates.append('ouvrage')

# pt
old_templates.append('citar web')
new_templates.append('lien web')

# sv
old_templates.append('webbref')
new_templates.append('lien web')

translated_templates_limit = len(new_templates)

# Templates with French aliases
old_templates.append('lien news')
new_templates.append('article')
# old_templates.append('webarchive') # TODO transform |url=https://web.archive.org/web/20161017215738/ to |horodatage archive=20161017215738|url=
# new_templates.append('lien archive')
old_templates.append('deadlink')
new_templates.append('lien brisé')
# old_template.append('dead link') TODO: if previous template is {{lien brisé}} then remove else replace
# new_template.append('lien brisé')
old_templates.append('lien brise')
new_templates.append('lien brisé')
old_templates.append('lien cassé')
new_templates.append('lien brisé')
old_templates.append('lien mort')
new_templates.append('lien brisé')
old_templates.append('lien web brisé')
new_templates.append('lien brisé')
old_templates.append('lien Web')
new_templates.append('lien web')
old_templates.append('site web')
new_templates.append('lien web')
old_templates.append('périodique')
new_templates.append('article')

# Templates to just translate their parameters
old_templates.append('lire en ligne')
new_templates.append('lire en ligne')
old_templates.append('dts')
new_templates.append('dts')
old_templates.append('Chapitre')
new_templates.append('Chapitre')
templates_limit = len(new_templates)

# Parameters to replace
old_param = []
new_param = []
old_param.append('author')
new_param.append('auteur')
old_param.append('authorlink1')
new_param.append('lien auteur1')
old_param.append('title')
new_param.append('titre')
old_param.append('script-title')
new_param.append('titre')
old_param.append('publisher')
new_param.append('éditeur')
# TODO write here those parameters, translated differently between {{lien web}} & {{article}}
old_param.append('work')
new_param.append('périodique')
old_param.append('newspaper')
new_param.append('journal')
old_param.append('day')
new_param.append('jour')
old_param.append('month')
new_param.append('mois')
old_param.append('year')
new_param.append('année')
old_param.append('accessdate')
new_param.append('consulté le')
old_param.append('access-date')
new_param.append('consulté le')
old_param.append('language')
new_param.append('langue')
old_param.append('lang')
new_param.append('langue')
old_param.append('quote')
new_param.append('extrait')
old_param.append('titre vo')
new_param.append('titre original')
old_param.append('first')
new_param.append('prénom')
old_param.append('surname')
new_param.append('nom')
old_param.append('last')
new_param.append('nom')
old_param.append('issue')
new_param.append('numéro')
old_param.append('authorlink')
new_param.append('lien auteur')
old_param.append('author-link')
new_param.append('lien auteur')
old_param.append('coauthorlink')
new_param.append('lien coauteur')
old_param.append('coauthor-link')
new_param.append('lien coauteur')
old_param.append('editor-first')
new_param.append('prénom')
old_param.append('editor-last')
new_param.append('nom')
for p in range(1, 20):
    old_param.append(f'first{str(p)}')
    new_param.append(f'prénom{str(p)}')
    old_param.append(f'given{str(p)}')
    new_param.append(f'prénom{str(p)}')
    old_param.append(f'last{str(p)}')
    new_param.append(f'nom{str(p)}')
    old_param.append(f'surname{str(p)}')
    new_param.append(f'nom{str(p)}')
    old_param.append(f'author{str(p)}')
    new_param.append(f'auteur{str(p)}')
    old_param.append(f'editor{str(p)}')
    new_param.append(f'auteur{str(p)}')
    old_param.append(f'authorlink{str(p)}')
    new_param.append(f'lien auteur{str(p)}')
    old_param.append(f'author{str(p)}link')
    new_param.append(f'lien auteur{str(p)}')
    # TODO Director params
    # old_param.append(f'editor{str(p)}-first')
    # new_param.append(f'prénom{str(p)}')
    # old_param.append(f'editor{str(p)}-last')
    # new_param.append(f'nom{str(p)}')
    # old_param.append(f'editor-first{str(p)}')
    # new_param.append(f'prénom{str(p)}')
    # old_param.append(f'editor-last{str(p)}')
    # new_param.append(f'nom{str(p)}')
old_param.append('coauthors')
new_param.append('coauteurs')
old_param.append('co-auteurs')
new_param.append('coauteurs')
old_param.append('co-auteur')
new_param.append('coauteur')
old_param.append('given')
new_param.append('prénom')
old_param.append('trad')
new_param.append('traducteur')
old_param.append('at')
new_param.append('passage')
old_param.append('origyear')
# TODO "année première impression" on sister projects
new_param.append('année première édition')
old_param.append('année première impression')
new_param.append('année première édition')
old_param.append('location')
new_param.append('lieu')
old_param.append('place')
new_param.append('lieu')
old_param.append('publication-date')
new_param.append('année')
old_param.append('writers')
new_param.append('scénario')
old_param.append('episodelink')
new_param.append('lien épisode')
old_param.append('serieslink')
new_param.append('lien série')
old_param.append('titlelink')
new_param.append('lien titre')
old_param.append('credits')
new_param.append('crédits')
old_param.append('network')
new_param.append('réseau')
old_param.append('station')
new_param.append('chaîne')
old_param.append('city')
new_param.append('ville')
old_param.append('began')
new_param.append('début')
old_param.append('ended')
new_param.append('fin')
old_param.append('airdate')
new_param.append('diffusion')
old_param.append('number')
new_param.append('numéro')
old_param.append('season')
new_param.append('saison')
old_param.append('year2')
new_param.append('année2')
old_param.append('month2')
new_param.append('mois2')
old_param.append('time')
new_param.append('temps')
old_param.append('accessyear')
new_param.append('année accès')
old_param.append('accessmonth')
new_param.append('mois accès')
old_param.append('conference')
new_param.append('conférence')
old_param.append('conferenceurl')
new_param.append('urlconférence')
old_param.append('booktitle')
new_param.append('titre livre')
old_param.append('others')
new_param.append('champ libre')
old_param.append('type')
new_param.append('nature ouvrage')
old_param.append('edition')
new_param.append('numéro d\'édition')
old_param.append('website')
new_param.append('périodique')
old_param.append('pp')
new_param.append('passage')
old_param.append('url-access')
new_param.append('accès url')
# TODO add for all templates?
# old_param.append('site')
# new_param.append('accès url')
old_param.append('doi-access')
new_param.append('accès doi')
old_param.append('hdl-access')
new_param.append('accès hdl')

# Fix
old_param.append('en ligne le')
new_param.append('archivedate')
old_param.append('autres')
new_param.append('champ libre')
old_param.append('Auteur')
new_param.append('auteur')
old_param.append('auteur-')
new_param.append('auteur')
old_param.append('consulté')
new_param.append('consulté le')
old_param.append('Consulté le')
new_param.append('consulté le')
old_param.append('consultée le')
new_param.append('consulté le')

# de
old_param.append('werk')
new_param.append('périodique')
old_param.append('titel')
new_param.append('titre')
old_param.append('TitelErg')
new_param.append('sous-titre')
old_param.append('titelerg')
new_param.append('sous-titre')
old_param.append('hrsg')
new_param.append('éditeur')
old_param.append('offline')
new_param.append('brisé le')
old_param.append('zugriff')
new_param.append('consulté le')
old_param.append('abruf')
new_param.append('consulté le')
old_param.append('archiv-url')
new_param.append('archiveurl')
old_param.append('archiv-datum')
new_param.append('archivedate')
old_param.append('autor')
new_param.append('auteur')
old_param.append('datum')
new_param.append('date')
old_param.append('datum-jahr')
new_param.append('année')
old_param.append('datum-monat')
new_param.append('mois')
old_param.append('datum-tag')
new_param.append('jour')
old_param.append('sprache')
new_param.append('langue')
old_param.append('seiten')
new_param.append('pages')
old_param.append('zitat')
new_param.append('citation')  # "extrait" ailleurs
old_param.append('kommentar')
new_param.append('description')

# es
old_param.append('autor')
new_param.append('auteur')
old_param.append('título')
new_param.append('titre')
old_param.append('fechaacceso')
new_param.append('consulté le')
old_param.append('fecha')
new_param.append('date')
old_param.append('obra')
new_param.append('série')
old_param.append('idioma')
new_param.append('langue')
old_param.append('publicació')
new_param.append('éditeur')
old_param.append('editorial')
new_param.append('journal')
old_param.append('series')
new_param.append('collection')
old_param.append('agency')
# TODO write here the alternatives when absent ("périodique")
new_param.append('auteur institutionnel')
old_param.append('magazine')
new_param.append('périodique')

# it
old_param.append('autore')
new_param.append('auteur')
old_param.append('titolo')
new_param.append('titre')
old_param.append('título')
new_param.append('titre')
old_param.append('accesso')
new_param.append('consulté le')
old_param.append('data')
new_param.append('date')
old_param.append('nome')
new_param.append('prénom')
old_param.append('cognome')
new_param.append('nom')
old_param.append('linkautore')
new_param.append('lien auteur')
old_param.append('coautori')
new_param.append('coauteurs')
old_param.append('rivista')
new_param.append('journal')
old_param.append('giorno')
new_param.append('jour')
old_param.append('mese')
new_param.append('mois')
old_param.append('anno')
new_param.append('année')
old_param.append('pagine')
new_param.append('page')
old_param.append('editore')
new_param.append('éditeur')

# pt
old_param.append('lingua')
new_param.append('langue')
old_param.append('titulo')
new_param.append('titre')
old_param.append('título')
new_param.append('titre')
old_param.append('primeiro')
new_param.append('prénom')
old_param.append('ultimo')
new_param.append('nom')
old_param.append('sobrenome')
new_param.append('nom')
old_param.append('apelido')
new_param.append('nom')
old_param.append('apellido')
new_param.append('nom')
old_param.append('data')
new_param.append('date')
old_param.append('obra')
new_param.append('série')
old_param.append('acessodata')
new_param.append('consulté le')
old_param.append('acessadoem')
new_param.append('consulté le')
old_param.append('fechaacceso')
new_param.append('consulté le')
old_param.append('publicado')
new_param.append('périodique')
old_param.append('periodical')
new_param.append('périodique')
old_param.append('arquivourl')
new_param.append('archiveurl')
old_param.append('deadurl')
new_param.append('archiveurl')
old_param.append('arquivodata')
new_param.append('archivedate')
old_param.append('formato')
new_param.append('format')
old_param.append('dia')
new_param.append('jour')
old_param.append('mes')
new_param.append('mois')
old_param.append('ano')
new_param.append('année')
old_param.append('pagina')
new_param.append('page')
old_param.append('página')
new_param.append('page')
old_param.append('citacao')
new_param.append('extrait')

# sv
old_param.append('författar')
new_param.append('auteur')
old_param.append('titel')
new_param.append('titre')
old_param.append('hämtdatum')
new_param.append('consulté le')
old_param.append('datum')
new_param.append('date')
old_param.append('förnamn')
new_param.append('prénom')
old_param.append('efternamn')
new_param.append('nom')
old_param.append('författarlänk')
new_param.append('lien auteur')
old_param.append('utgivare')
new_param.append('éditeur')
old_param.append('månad')
new_param.append('mois')
old_param.append('år')
new_param.append('année')
old_param.append('sida')
new_param.append('page')
old_param.append('verk')
new_param.append('périodique')

param_limit = len(old_param)
if param_limit != len(new_param):
    input('Fatal error: unbalanced new and old parameters')
