python redirect.py double -always -family:wikipedia -lang:ar
python redirect.py double -always -family:wikipedia -lang:de
python redirect.py double -always -family:wikipedia -lang:el
python redirect.py double -always -family:wikipedia -lang:es
python redirect.py double -always -family:wikipedia -lang:gl
python redirect.py double -always -family:wikipedia -lang:he
python redirect.py double -always -family:wikipedia -lang:hi
python redirect.py double -always -family:wikipedia -lang:id
python redirect.py double -always -family:wikipedia -lang:ja
python redirect.py double -always -family:wikipedia -lang:la
python redirect.py double -always -family:wikipedia -lang:pt
python redirect.py double -always -family:wikipedia -lang:ru
python redirect.py double -always -family:wikipedia -lang:tr
python redirect.py double -always -family:wikipedia -lang:vi
python redirect.py double -always -family:wikipedia -lang:zh

python redirect.py double -always -family:wiktionary -lang:ar
python redirect.py double -always -family:wiktionary -lang:de
python redirect.py double -always -family:wiktionary -lang:el
python redirect.py double -always -family:wiktionary -lang:es
python redirect.py double -always -family:wiktionary -lang:gl
python redirect.py double -always -family:wiktionary -lang:he
python redirect.py double -always -family:wiktionary -lang:hi
python redirect.py double -always -family:wiktionary -lang:id
python redirect.py double -always -family:wiktionary -lang:ja
python redirect.py double -always -family:wiktionary -lang:la
python redirect.py double -always -family:wiktionary -lang:pt
python redirect.py double -always -family:wiktionary -lang:ru
python redirect.py double -always -family:wiktionary -lang:tr
python redirect.py double -always -family:wiktionary -lang:vi
python redirect.py double -always -family:wiktionary -lang:zh

python redirect.py double -always -family:wikiversity -lang:ar
python redirect.py double -always -family:wikiversity -lang:de
python redirect.py double -always -family:wikiversity -lang:el
python redirect.py double -always -family:wikiversity -lang:es
python redirect.py double -always -family:wikiversity -lang:gl
python redirect.py double -always -family:wikiversity -lang:he
python redirect.py double -always -family:wikiversity -lang:hi
python redirect.py double -always -family:wikiversity -lang:id
python redirect.py double -always -family:wikiversity -lang:ja
python redirect.py double -always -family:wikiversity -lang:la
python redirect.py double -always -family:wikiversity -lang:pt
python redirect.py double -always -family:wikiversity -lang:ru
python redirect.py double -always -family:wikiversity -lang:tr
python redirect.py double -always -family:wikiversity -lang:vi
python redirect.py double -always -family:wikiversity -lang:zh

python redirect.py double -always -family:wikibooks -lang:ar
python redirect.py double -always -family:wikibooks -lang:de
python redirect.py double -always -family:wikibooks -lang:el
python redirect.py double -always -family:wikibooks -lang:es
python redirect.py double -always -family:wikibooks -lang:gl
python redirect.py double -always -family:wikibooks -lang:he
python redirect.py double -always -family:wikibooks -lang:hi
python redirect.py double -always -family:wikibooks -lang:id
python redirect.py double -always -family:wikibooks -lang:ja
python redirect.py double -always -family:wikibooks -lang:la
python redirect.py double -always -family:wikibooks -lang:pt
python redirect.py double -always -family:wikibooks -lang:ru
python redirect.py double -always -family:wikibooks -lang:tr
python redirect.py double -always -family:wikibooks -lang:vi
python redirect.py double -always -family:wikibooks -lang:zh

python redirect.py double -always -family:wikisource -lang:ar
python redirect.py double -always -family:wikisource -lang:de
python redirect.py double -always -family:wikisource -lang:el
python redirect.py double -always -family:wikisource -lang:es
python redirect.py double -always -family:wikisource -lang:gl
python redirect.py double -always -family:wikisource -lang:he
python redirect.py double -always -family:wikisource -lang:hi
python redirect.py double -always -family:wikisource -lang:id
python redirect.py double -always -family:wikisource -lang:ja
python redirect.py double -always -family:wikisource -lang:la
python redirect.py double -always -family:wikisource -lang:pt
python redirect.py double -always -family:wikisource -lang:ru
python redirect.py double -always -family:wikisource -lang:tr
python redirect.py double -always -family:wikisource -lang:vi
python redirect.py double -always -family:wikisource -lang:zh

python redirect.py double -always -family:wikiquote -lang:ar
python redirect.py double -always -family:wikiquote -lang:de
python redirect.py double -always -family:wikiquote -lang:el
python redirect.py double -always -family:wikiquote -lang:es
python redirect.py double -always -family:wikiquote -lang:gl
python redirect.py double -always -family:wikiquote -lang:he
python redirect.py double -always -family:wikiquote -lang:hi
python redirect.py double -always -family:wikiquote -lang:id
python redirect.py double -always -family:wikiquote -lang:ja
python redirect.py double -always -family:wikiquote -lang:la
python redirect.py double -always -family:wikiquote -lang:pt
python redirect.py double -always -family:wikiquote -lang:ru
python redirect.py double -always -family:wikiquote -lang:tr
python redirect.py double -always -family:wikiquote -lang:vi
python redirect.py double -always -family:wikiquote -lang:zh

python redirect.py double -always -family:wikinews -lang:ar
python redirect.py double -always -family:wikinews -lang:de
python redirect.py double -always -family:wikinews -lang:el
python redirect.py double -always -family:wikinews -lang:es
python redirect.py double -always -family:wikinews -lang:gl
python redirect.py double -always -family:wikinews -lang:he
python redirect.py double -always -family:wikinews -lang:hi
python redirect.py double -always -family:wikinews -lang:id
python redirect.py double -always -family:wikinews -lang:ja
python redirect.py double -always -family:wikinews -lang:la
python redirect.py double -always -family:wikinews -lang:pt
python redirect.py double -always -family:wikinews -lang:ru
python redirect.py double -always -family:wikinews -lang:tr
python redirect.py double -always -family:wikinews -lang:vi
python redirect.py double -always -family:wikinews -lang:zh

python redirect.py double -always -family:wikivoyage -lang:ar
python redirect.py double -always -family:wikivoyage -lang:de
python redirect.py double -always -family:wikivoyage -lang:el
python redirect.py double -always -family:wikivoyage -lang:es
python redirect.py double -always -family:wikivoyage -lang:gl
python redirect.py double -always -family:wikivoyage -lang:he
python redirect.py double -always -family:wikivoyage -lang:hi
python redirect.py double -always -family:wikivoyage -lang:id
python redirect.py double -always -family:wikivoyage -lang:ja
python redirect.py double -always -family:wikivoyage -lang:la
python redirect.py double -always -family:wikivoyage -lang:pt
python redirect.py double -always -family:wikivoyage -lang:ru
python redirect.py double -always -family:wikivoyage -lang:tr
python redirect.py double -always -family:wikivoyage -lang:vi
python redirect.py double -always -family:wikivoyage -lang:zh
pause