#!/usr/bin/env python
# coding: utf-8
"""
List of the templates to replace
"""
from __future__ import absolute_import, unicode_literals

old_templates = {
    '-': '',
    'Citation needed': 'référence nécessaire',
    'Référence nécessaire': 'référence nécessaire',
    'abrev': 'abréviation',
    'abrév': 'abréviation',
    'absol': 'absolument',
    'acron': 'acronyme',
    'analogie': 'par analogie',
    'angl': 'anglicisme',
    'arbre': 'arbres',
    'arch': 'archaïsme',
    'archaïque': 'archaïsme',
    'b-m-cour': 'beaucoup moins courant',
    'boîte début': '(',
    'boîte fin': ')',
    'cardin': 'cardinal',
    'clef de tri': 'clé de tri',
    'coll': 'collectif',
    'comp': 'comparatif',
    'compos': 'composé de',
    'contr': 'contraction',
    'cour': 'courant',
    'cours d\'eau': 'cours d’eau',
    'didact': 'didactique',
    'dén': 'dénombrable',
    'dés': 'désuet',
    'dét': 'déterminé',
    'en-nom-rég-double': 'en-nom-rég',
    'euph': 'par euphémisme',
    'euphémisme': 'par euphémisme',
    'ex': 'e',
    'ex-rare': 'extrêmement rare',
    'exagération': 'par hyperbole',
    'fam': 'familier',
    'femin': 'au féminin',
    'fig': 'figuré',
    'fp': 'fplur',
    'fs': 'fsing',
    'fémin': 'au féminin',
    'gall': 'gallicisme',
    'humour': 'par plaisanterie',
    'hyperb': 'par hyperbole',
    'hyperbole': 'par hyperbole',
    'imperf': 'imperfectif',
    'injur': 'injurieux',
    'ironie': 'ironique',
    'irrég': 'irrégulier',
    'litt': 'littéraire',
    'légume': 'légumes',
    'mascul': 'au masculin',
    'mp': 'mplur',
    'méton': 'par métonymie',
    'métonymie': 'par métonymie',
    'nomin': 'nominatif',
    'np': 'nlur',
    'néol': 'néologisme',
    'oiseau': 'oiseaux',
    'ordin': 'ordinal',
    'par ext': 'par extension',
    'part': 'en particulier',
    'partic': 'en particulier',
    'particulier': 'en particulier',
    'perf': 'perfectif',
    'pl-cour': 'plus courant',
    'pl-rare': 'plus rare',
    'plais': 'par plaisanterie',
    'plaisanterie': 'par plaisanterie',
    'plante': 'plantes',
    'plur': 'au pluriel',
    'pluri': 'au pluriel',
    'poét': 'poétique',
    'pron-rég': 'écouter',
    'péj': 'péjoratif',
    'régio': 'région',
    'sing': 'au singulier',
    'super': 'superlatif',
    'terme': 'term',
    'trad--': 'trad',
    'très-rare': 'très rare',
    'vêtement': 'vêtements',
    'vx': 'vieilli',
}

old_language_templates = {
    'arg': 'an',
    'be-x-old': 'be-tarask',
    'gaul': 'gaulois',
    'gsw-FR': 'gsw-fr',
    'ko-hanja': 'ko-Hani',
    'lsf': 'fsl',
    'nav': 'nv',
    'nds-NL': 'nds-nl',
    'prv': 'oc',
    'roa-rup': 'rup',
    'xtg': 'gaulois',
    'zh-min-nan': 'nan',
    'zh-sc': 'zh-Hans',
}
# TODO vi-Hani ?
