name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Quality
#        run: |
#              pylint $(git ls-files '*.py')
#              find . -name '*.py' -exec autopep8 --in-place '{}' \;:
#              sourcery review src/wiktionary/fr_wiktionary_functions.py
      - name: Test
        run: |
              python tests/fr_wiktionary_functions_test.py
